### ISSUE TITLE
How to get "malicious_labels.txt"

### ISSUE THREAD

**Issue by lesleychou** [purseclab/ATLAS#2]
Hi Alsaheel,

May I ask how did you get the "malicious_labels.txt (inside training/testing logs)" from raw logs? 
Does the "prepocess.py" assume that "malicious_labels.txt" already exists?

**Comment by lesleychou** [comment]
I found the answer inside the paper, I'm sure these are known beforehand from the ground truth.

**Comment by cssaheel** [comment]
That's right, the malicious_labels.txt list a labels (entities) that is used by ATLAS during Training phase for model learning, and during the Testing phase for evaluation purposes.
