### ISSUE TITLE
missing files from the experiments

### ISSUE THREAD

**Issue by matthew-renodin** [purseclab/ATLAS#5]
I was just reviewing the contents and trying to run your experiments. I unpacked S1 and tried to execute the preprocess function. It was missing the files in the logs directories of the training and testing.

**Comment by Vmasks** [comment]
Copy from raw_logs folders manually.

**Comment by cssaheel** [comment]
You could either change the files location, or change the preprocess code to look for these files. S1 has all the needed files but you will need to place the files where they are expected. Thanks.
